### ISSUE TITLE
코딩 고수가 되자!

### ISSUE THREAD

**Issue by Mingking9891** [2021-SMHRD-KDT-New-Bigdata-1/whitebeard#4]
- [x] 파이썬 마스터
- [x] 자바 마스터
- [x] 데이터베이스 마스터
- [x] HTML/CSS 마스터
- [x] 자바스크립트 마스터
- [x] 크롤링 마스터
- [x] 아무튼 마스터

**Comment by Mingking9891** [comment]
가즈아

**Comment by witchking9494** [comment]
해치울까요...마스터...?
